def mapCodeToActivity(activityCode):
    """
    Maps activity codes to their corresponding activity names.
    """
    activity_map = {
        0: "Bring",
        1: "Clean Floor",
        2: "Clean Surface",
        3: "Close Big Box",
        4: "Close Door",
        5: "Close Drawer",
        6: "Close Lid By Rotate",
        7: "Close Other Lid",
        8: "Close Small Box",
        9: "Close Tap Water",
        10: "Drink",
        11: "Dry Off Hands",
        12: "Dry Off Hands By Shake",
        13: "Eat Small",
        14: "Gargle",
        15: "Getting Up",
        16: "Hang",
        17: "Lying Down",
        18: "Open Bag",
        19: "Open Big Box",
        20: "Open Door",
        21: "Open Drawer",
        22: "Open Lid By Rotate",
        23: "Open Other Lid",
        24: "Open Small Box",
        25: "Open Tap Water",
        26: "Plug In",
        27: "Press By Grasp",
        28: "Press From Top",
        29: "Press Switch",
        30: "Put From Bottle",
        31: "Put From Tap Water",
        32: "Put High Position",
        33: "Put On Floor",
        34: "Read",
        35: "Rotate",
        36: "Rub Hands",
        37: "Scoop And Put",
        38: "Sitting Down",
        39: "Squatting Down",
        40: "Standing Up",
        41: "Stand Up From Squatting",
        42: "Take From Floor",
        43: "Take From High Position",
        44: "Take Off Jacket",
        45: "Take Out",
        46: "Talk By Telephone",
        47: "Throw Out",
        48: "Throw Out Water",
        49: "Touch Smartphone Screen",
        50: "Type",
        51: "Unhang",
        52: "Unplug",
        53: "Wear Jacket",
        54: "Write"
    }

    return activity_map.get(activityCode, "Unknown Activity")